//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingHistory
    {
        public int Id { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string VehicleName { get; set; }
        public string VehicleModel { get; set; }
    
        public virtual User User { get; set; }
    }
}
