//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BookingHistories = new HashSet<BookingHistory>();
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual ICollection<BookingHistory> BookingHistories { get; set; }
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
