//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRentalSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public Vehicle()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> RatePerDay { get; set; }
        public string ImagePath { get; set; }
        public string Model { get; set; }
        public string EngineCapacity { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
    }
}
